//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalDocument
    {
        public long EmployeeId { get; set; }
        public bool TemporaryLivingAllowance { get; set; }
        public bool Passport { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> PassportIssueDate { get; set; }
        public Nullable<System.DateTime> PassportExpiredDate { get; set; }
        public bool VISA { get; set; }
        public string VISANumber { get; set; }
        public Nullable<System.DateTime> VISAExpiredDate { get; set; }
        public bool NationalityVerification { get; set; }
        public bool WorkPermit { get; set; }
        public string WorkPermitNumber { get; set; }
        public Nullable<System.DateTime> WorkPermitExpiredDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
