//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCheque
    {
        public long ARPaymentId { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public long BankId { get; set; }
        public string ChequeNumber { get; set; }
        public int ChequeStatusId { get; set; }
    
        public virtual ARPayment ARPayment { get; set; }
        public virtual Bank Bank { get; set; }
        public virtual ChequeStatu ChequeStatu { get; set; }
    }
}
