//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public Bill()
        {
            this.BillARPayments = new HashSet<BillARPayment>();
        }
    
        public long Id { get; set; }
        public string Number { get; set; }
        public decimal Amount { get; set; }
        public long CompanyId { get; set; }
        public System.DateTime BillDate { get; set; }
        public long CustomerId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<BillARPayment> BillARPayments { get; set; }
    }
}
