//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Bill
    {
        public Bill()
        {
            this.BillARPayments = new HashSet<BillARPayment>();
        }

        public long Id { get; set; }
        [Required]
        public string Number { get; set; }
        [Required]
        [DataType(DataType.Currency)]
        public decimal Amount { get; set; }
        [Required]
        public long CompanyId { get; set; }
        [Required]
        public System.DateTime BillDate { get; set; }
        [Required]
        public long CustomerId { get; set; }
        [Required]
        public int BillStatusId { get; set; }
        public string Remark { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<BillARPayment> BillARPayments { get; set; }
        public virtual BillStatus BillStatus { get; set; }
    }
}
