//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyBankAccount
    {
        public long CompanyId { get; set; }
        public string AccountNumber { get; set; }
        public long BankId { get; set; }
        public string Name { get; set; }
        public int AccountTypeId { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual Bank Bank { get; set; }
        public virtual Company Company { get; set; }
    }
}
