//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public long Id { get; set; }
        [Required]
        public string Firstname { get; set; }
        [Required]
        public string Lastname { get; set; }
        [Required]
        public string Gender { get; set; }
        public string Alias { get; set; }
        public string NationalIdentificationNumber { get; set; }
        public string TelephoneNumber { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        [DataType(DataType.Text)]
        public Nullable<System.DateTime> BirthDate { get; set; }
        [DataType(DataType.Text)]
        public Nullable<System.DateTime> StartWorkingDate { get; set; }
        [Required]
        public int WorkingStatusId { get; set; }
        [Required]
        public long NationalityId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    
        public virtual AdditionalDocument AdditionalDocument { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual WorkingStatus WorkingStatus { get; set; }
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual Department Department { get; set; }
    }
}
