//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GGPDBEntities : DbContext
    {
        public GGPDBEntities()
            : base("name=GGPDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARCheque> ARCheques { get; set; }
        public virtual DbSet<ARPayment> ARPayments { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<BillARPayment> BillARPayments { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerContact> CustomerContacts { get; set; }
        public virtual DbSet<AdditionalDocument> AdditionalDocuments { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Nationality> Nationalities { get; set; }
        public virtual DbSet<WorkingStatus> WorkingStatus { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<ChequeStatus> ChequeStatus { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<SupplierContact> SupplierContacts { get; set; }
        public virtual DbSet<UnifOfMeasurement> UnifOfMeasurements { get; set; }
        public virtual DbSet<BillStatus> BillStatus { get; set; }
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<CompanyBankAccount> CompanyBankAccounts { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
    }
}
