//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public long CompanyId { get; set; }
        public long CustomerId { get; set; }
        public string ItemName { get; set; }
        public decimal Quantity { get; set; }
        public long UnitOfMeasurementId { get; set; }
        public decimal PricePerUnit { get; set; }
        public string Place { get; set; }
        public string Remark { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Company Company { get; set; }
        public virtual UnifOfMeasurement UnifOfMeasurement { get; set; }
    }
}
